export const MOOD_COLORS = [
  // Original 12
  { color: '#FFD700', name: 'Freudig' },
  { color: '#40E0D0', name: 'Ruhig' },
  { color: '#FF4500', name: 'Energetisch' },
  { color: '#4169E1', name: 'Traurig' },
  { color: '#8A2BE2', name: 'Kreativ' },
  { color: '#FF1493', name: 'Aufgeregt' },
  { color: '#ADFF2F', name: 'Frisch' },
  { color: '#708090', name: 'Neutral' },
  { color: '#FF8C00', name: 'Mutig' },
  { color: '#00CED1', name: 'Friedlich' },
  { color: '#8B4513', name: 'Geerdet' },
  { color: '#1C1C3E', name: 'Geheimnisvoll' },
  // New 12
  { color: '#FF69B4', name: 'Verliebt' },
  { color: '#7CFC00', name: 'Dankbar' },
  { color: '#6A5ACD', name: 'Einsam' },
  { color: '#FFA500', name: 'Optimistisch' },
  { color: '#A9A9A9', name: 'Erschöpft' },
  { color: '#00FA9A', name: 'Neugierig' },
  { color: '#DC143C', name: 'Wütend' },
  { color: '#DAA520', name: 'Stolz' },
  { color: '#9370DB', name: 'Ängstlich' },
  { color: '#87CEEB', name: 'Entspannt' },
  { color: '#FF6347', name: 'Inspiriert' },
  { color: '#D2691E', name: 'Nostalgisch' },
  // Row 3: additional moods
  { color: '#98FF98', name: 'Minzig' },
  { color: '#B57EDC', name: 'Sanftmütig' },
  { color: '#FF7F50', name: 'Herzlich' },
  { color: '#FFBF00', name: 'Zuversichtlich' },
  { color: '#778899', name: 'Gelassen' },
  { color: '#FF007F', name: 'Leidenschaftlich' },
  { color: '#32CD32', name: 'Lebendig' },
  { color: '#E6E6FA', name: 'Verträumt' },
];

export const THEME_ICONS = [
  { id: 'classic', name: 'Klassisch', price: 0, preview: 'sunny' },
  { id: 'gaming', name: 'Gaming', price: 500, preview: 'game-controller' },
  { id: 'food', name: 'Essen', price: 500, preview: 'pizza' },
  { id: 'nature', name: 'Natur', price: 500, preview: 'leaf' },
  { id: 'retro', name: 'Retro', price: 500, preview: 'videocam' },
  { id: 'minimal', name: 'Minimal', price: 500, preview: 'square' },
];

export const THEME_MOODS: Record<string, { icon: string }[]> = {
  classic: [
    { icon: 'sunny' }, { icon: 'water' }, { icon: 'flash' }, { icon: 'rainy' },
    { icon: 'color-wand' }, { icon: 'heart' }, { icon: 'leaf' }, { icon: 'remove-circle' },
    { icon: 'shield' }, { icon: 'cloud' }, { icon: 'planet' }, { icon: 'moon' },
    { icon: 'heart-outline' }, { icon: 'flower' }, { icon: 'telescope' }, { icon: 'compass' },
    { icon: 'ribbon' }, { icon: 'sparkles' }, { icon: 'bulb' }, { icon: 'eye' },
    { icon: 'gift' }, { icon: 'bookmark' }, { icon: 'aperture' }, { icon: 'rose' },
    { icon: 'snow' }, { icon: 'wine' }, { icon: 'flame' }, { icon: 'star' },
    { icon: 'partly-sunny' }, { icon: 'bonfire' }, { icon: 'earth' }, { icon: 'cloudy-night' },
  ],
  gaming: [
    { icon: 'game-controller' }, { icon: 'trophy' }, { icon: 'skull' }, { icon: 'shield-half' },
    { icon: 'diamond' }, { icon: 'heart' }, { icon: 'star' }, { icon: 'medal' },
    { icon: 'disc' }, { icon: 'play' }, { icon: 'pause' }, { icon: 'headset' },
    { icon: 'speedometer' }, { icon: 'rocket' }, { icon: 'terminal' }, { icon: 'power' },
    { icon: 'trending-up' }, { icon: 'pulse' }, { icon: 'refresh' }, { icon: 'flag' },
    { icon: 'options' }, { icon: 'grid' }, { icon: 'layers' }, { icon: 'construct' },
    { icon: 'flash' }, { icon: 'planet' }, { icon: 'flame' }, { icon: 'compass' },
    { icon: 'hourglass' }, { icon: 'color-wand' }, { icon: 'leaf' }, { icon: 'sparkles' },
  ],
  food: [
    { icon: 'pizza' }, { icon: 'ice-cream' }, { icon: 'cafe' }, { icon: 'beer' },
    { icon: 'wine' }, { icon: 'fast-food' }, { icon: 'nutrition' }, { icon: 'restaurant' },
    { icon: 'egg' }, { icon: 'fish' }, { icon: 'pint' }, { icon: 'flask' },
    { icon: 'storefront' }, { icon: 'bag' }, { icon: 'star' }, { icon: 'leaf' },
    { icon: 'flower' }, { icon: 'gift' }, { icon: 'ribbon' }, { icon: 'ticket' },
    { icon: 'bookmark' }, { icon: 'globe' }, { icon: 'happy' }, { icon: 'heart' },
    { icon: 'snow' }, { icon: 'sparkles' }, { icon: 'flame' }, { icon: 'sunny' },
    { icon: 'water' }, { icon: 'rose' }, { icon: 'nutrition' }, { icon: 'cloudy-night' },
  ],
  nature: [
    { icon: 'leaf' }, { icon: 'flower' }, { icon: 'bonfire' }, { icon: 'cloud' },
    { icon: 'rainy' }, { icon: 'sunny' }, { icon: 'snow' }, { icon: 'thunderstorm' },
    { icon: 'rose' }, { icon: 'tree' }, { icon: 'water' }, { icon: 'flame' },
    { icon: 'telescope' }, { icon: 'sparkles' }, { icon: 'earth' }, { icon: 'globe' },
    { icon: 'bulb' }, { icon: 'compass' }, { icon: 'aperture' }, { icon: 'pulse' },
    { icon: 'heart-outline' }, { icon: 'gift' }, { icon: 'ribbon' }, { icon: 'eye' },
    { icon: 'partly-sunny' }, { icon: 'cloudy-night' }, { icon: 'moon' }, { icon: 'star' },
    { icon: 'planet' }, { icon: 'color-wand' }, { icon: 'flash' }, { icon: 'diamond' },
  ],
  retro: [
    { icon: 'tv' }, { icon: 'radio' }, { icon: 'camera' }, { icon: 'videocam' },
    { icon: 'recording' }, { icon: 'mic' }, { icon: 'musical-notes' }, { icon: 'headset' },
    { icon: 'calculator' }, { icon: 'watch' }, { icon: 'hourglass' }, { icon: 'magnet' },
    { icon: 'film' }, { icon: 'key' }, { icon: 'mail' }, { icon: 'map' },
    { icon: 'compass' }, { icon: 'bookmark' }, { icon: 'flag' }, { icon: 'ticket' },
    { icon: 'ribbon' }, { icon: 'gift' }, { icon: 'aperture' }, { icon: 'telescope' },
    { icon: 'flash' }, { icon: 'disc' }, { icon: 'flame' }, { icon: 'star' },
    { icon: 'planet' }, { icon: 'color-wand' }, { icon: 'leaf' }, { icon: 'sparkles' },
  ],
  minimal: [
    { icon: 'square' }, { icon: 'ellipse' }, { icon: 'triangle' }, { icon: 'star' },
    { icon: 'heart' }, { icon: 'close' }, { icon: 'add' }, { icon: 'remove' },
    { icon: 'play' }, { icon: 'pause' }, { icon: 'stop' }, { icon: 'radio-button-on' },
    { icon: 'checkmark' }, { icon: 'arrow-up' }, { icon: 'arrow-down' }, { icon: 'arrow-forward' },
    { icon: 'refresh' }, { icon: 'sync' }, { icon: 'share' }, { icon: 'expand' },
    { icon: 'funnel' }, { icon: 'swap-horizontal' }, { icon: 'options' }, { icon: 'grid' },
    { icon: 'diamond' }, { icon: 'key' }, { icon: 'flash' }, { icon: 'flag' },
    { icon: 'planet' }, { icon: 'leaf' }, { icon: 'snow' }, { icon: 'cloudy-night' },
  ],
};
